apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c7x280icy-nodejs
  janus-idp.io/tekton: c7x280icy-nodejs
  backstage.io/kubernetes-id: c7x280icy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c7x280icy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
